version: '3.8'

services:
  frontend:
    build: .
    ports:
      - "80:80"
    restart: unless-stopped
    container_name: rsgo-frontend
    networks:
      - rsgo-network

networks:
  rsgo-network:
    external: true